server:
  # 端口
  port: 9001
  servlet:
    context-path: /

spring:
  application:
    # 服务名称
    name: micro-user

# # 服务生产者
eureka:
  client:
    # 获取注册信息（消费服务）
    fetch-registry: true
    # 注册该服务（生产服务）
    register-with-eureka: true
    # 注册服务地址
    service-url:
      defaultZone: http://127.0.0.1:8888/eureka
  instance:
    # 优先使用IP地址进行注册，强烈建议
    prefer-ip-address: true
    # 服务续约间隔（心跳），默认30秒（单位秒）
    lease-renewal-interval-in-seconds: 30
    # 服务失效时间，默认90秒（单位秒）
    lease-expiration-duration-in-seconds: 90
